void getNewAngle(int*, char);
int canMoveForward(int*, char*[], int);
int atMarker(int*, char*[]);
int checks(int*, char*[], int);
void forward(int*, char*[], int);
void left(int*, int*);
void right(int*, int*);
void backward(int*, char*[], int*);
void instructionsStage1(int*, char*[], int*);
void start();
void startStage1_2(char*[]);
void startStage3(char*[]);
